image: node:12

pipelines:
  default:
    - step:
        name: CI
        trigger: automatic
        caches:
          - node
        script:
          - cp .npmrc-conf ~/.npmrc
          - npm ci
          - npm test
  pull-requests:
    task/*:
      - step:
          name: CI - staging
          trigger: automatic
          script:
            - cp .npmrc-conf ~/.npmrc
            - npm ci
            - npm test
          artifacts:
            - node_modules/**
      - step:
          name: CD - staging - west
          trigger: manual
          script:
            - cp .npmrc-conf ~/.npmrc
            - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
            - export AWS_ROLE=$DEV_AWS_ROLE
            - npm run dp:stg:w
          artifacts:
            - node_modules/**
      - step:
          name: CD - staging - east
          trigger: manual
          script:
            - cp .npmrc-conf ~/.npmrc
            - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
            - export AWS_ROLE=$DEV_AWS_ROLE
            - npm run dp:stg:e
  branches:
    master:
      - step:
          name: CI - production
          trigger: automatic
          script:
            - cp .npmrc-conf ~/.npmrc
            - npm ci
            - npm test
          artifacts:
            - node_modules/**
      - step:
          name: CD - production - west
          trigger: automatic
          script:
            - cp .npmrc-conf ~/.npmrc
            - export AWS_ACCESS_KEY_ID=$PRD_AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$PRD_AWS_SECRET_ACCESS_KEY
            - export AWS_ROLE=$PRD_AWS_ROLE
            - npm run dp:prd:w
          artifacts:
            - node_modules/**
      - step:
          name: CD - production - east
          trigger: manual
          script:
            - cp .npmrc-conf ~/.npmrc
            - export AWS_ACCESS_KEY_ID=$PRD_AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$PRD_AWS_SECRET_ACCESS_KEY
            - export AWS_ROLE=$PRD_AWS_ROLE
            - npm run dp:prd:e
